create_hdl_core -file $kronus::project_dir/hdl/miv_ihcc.v -module {MIV_IHCC} -library {work} -package {}
hdl_core_add_bif -hdl_core_name {MIV_IHCC} -bif_definition {APB:AMBA:AMBA2:slave} -bif_name {A_SIDE} -signal_map {}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PADDR} -core_signal_name {a_paddr}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PENABLE} -core_signal_name {a_penable}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PWRITE} -core_signal_name {a_pwrite}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PRDATA} -core_signal_name {a_prdata}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PWDATA} -core_signal_name {a_pwdata}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PREADY} -core_signal_name {a_pready}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PSLVERR} -core_signal_name {a_pslverr}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {A_SIDE} -bif_signal_name {PSELx} -core_signal_name {a_psel}
hdl_core_add_bif -hdl_core_name {MIV_IHCC} -bif_definition {APB:AMBA:AMBA2:slave} -bif_name {B_SIDE} -signal_map {}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PADDR} -core_signal_name {b_paddr}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PENABLE} -core_signal_name {b_penable}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PWRITE} -core_signal_name {b_pwrite}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PRDATA} -core_signal_name {b_prdata}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PWDATA} -core_signal_name {b_pwdata}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PREADY} -core_signal_name {b_pready}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PSLVERR} -core_signal_name {b_pslverr}
hdl_core_assign_bif_signal -hdl_core_name {MIV_IHCC} -bif_name {B_SIDE} -bif_signal_name {PSELx} -core_signal_name {b_psel}
